# -*- coding: utf-8 -*-
"""YT_Video_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGCuIq9b6ouBJxSHbtcyEKJ3fScRAjur
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("TREND.csv")
print(df.head())

df.info()
df.isnull().sum()
df.describe()

df['trending_date'] = pd.to_datetime(df['trending_date'], format='%y.%d.%m')
df['publish_time'] = pd.to_datetime(df['publish_time'])
df['publish_hour'] = df['publish_time'].dt.hour
df['publish_day'] = df['publish_time'].dt.day_name()

top_channels = df['channel_title'].value_counts().head(10)
sns.barplot(x=top_channels.values, y=top_channels.index)
plt.title("Top 10 Trending Channels")
plt.xlabel("Number of Trending Videos")
plt.show()

category_mapping = {
    1: "Film & Animation", 2: "Autos & Vehicles", 10: "Music",
    15: "Pets & Animals", 17: "Sports", 20: "Gaming",
    22: "People & Blogs", 23: "Comedy", 24: "Entertainment",
    25: "News & Politics", 26: "Howto & Style", 27: "Education",
    28: "Science & Technology", 29: "Nonprofits & Activism"
}

df['category'] = df['category_id'].map(category_mapping)

category_views = df.groupby("category")['views'].mean().sort_values(ascending=False)
sns.barplot(x=category_views.values, y=category_views.index)
plt.title("Average Views per Category")
plt.xlabel("Views")
plt.show()

sns.heatmap(df[['views', 'likes', 'dislikes', 'comment_count']].corr(), annot=True)
plt.title("Correlation Between Metrics")
plt.show()

sns.boxplot(x='publish_hour', y='views', data=df)
plt.title("Views Distribution by Publish Hour")
plt.show()

df['title_len'] = df['title'].apply(len)
df['tag_count'] = df['tags'].apply(lambda x: len(x.split('|')))

sns.scatterplot(x='title_len', y='views', data=df)
plt.title("Title Length vs Views")
plt.show()

video_trend_days = df.groupby('video_id').size().sort_values(ascending=False).head(10)
print(video_trend_days)



